name: Build Xdroid 14 GSI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout (buat folder kerja)
      run: |
        mkdir xdroid
        cd xdroid
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"

    - name: Install dependencies
  run: |
    sudo apt-get update || true
    sudo DEBIAN_FRONTEND=noninteractive apt-get install -yq \
      bc bison build-essential curl flex g++-multilib gcc-multilib git \
      gnupg gperf imagemagick libncurses-dev lib32z1-dev liblz4-tool \
      libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils \
      lzop openjdk-11-jdk pngcrush rsync schedtool squashfs-tools \
      xsltproc zip zlib1g-dev repo
      
    - name: Init repo
      run: |
        cd xdroid
        repo init -u https://github.com/XDroid-OSS/manifest -b fourteen
        repo sync --force-sync --no-tags --no-clone-bundle -j1

    - name: Apply TrebleDroid patches
      run: |
        cd xdroid
        git clone https://github.com/phhusson/treble_experimentations treble
        bash treble/apply-patches.sh

    - name: Setup build environment
      run: |
        cd xdroid
        source build/envsetup.sh
        lunch xdroid_arm64_ab-userdebug

    - name: Build system image
      run: |
        cd xdroid
        make systemimage -j$(nproc)

    - name: Upload system.img
      uses: actions/upload-artifact@v4
      with:
        name: system-img
        path: xdroid/out/target/product/*/system.img
