name: Build Xdroid 14 GSI

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout TrebleDroid
        uses: actions/checkout@v3

      - name: Install dependencies
  run: |
    sudo apt-get update || true
    sudo DEBIAN_FRONTEND=noninteractive apt-get install -yq \
      bc bison build-essential curl flex g++-multilib gcc-multilib git \
      gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev \
      lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev \
      libxml2 libxml2-utils lzop openjdk-11-jdk pngcrush rsync \
      schedtool squashfs-tools xsltproc zip zlib1g-dev repo
      
      - name: Init repo
        run: |
          mkdir xdroid
          cd xdroid
          repo init -u https://github.com/XDroid-OSS/manifest -b fourteen
          repo sync -c --no-tags --no-clone-bundle -j4

      - name: Apply GSI patches
        run: |
          cd xdroid
          git clone https://github.com/phhusson/treble_experimentations treble
          bash treble/apply-patches.sh

      - name: Setup environment
        run: |
          cd xdroid
          source build/envsetup.sh
          lunch xdroid_arm64_ab-userdebug

      - name: Build GSI
        run: |
          cd xdroid
          make systemimage -j$(nproc)

      - name: Upload system image
        uses: actions/upload-artifact@v4
        with:
          name: system-img
          path: xdroid/out/target/product/*/system.img
